HAI 1.2
I HAS A INPUT BTW declaring input variable
VISIBLE "GIMMEH YUR VARIABLE: " !
GIMMEH INPUT
INPUT IS NOW A NUMBR
BOTH SAEM INPUT  0, O RLY?
	YA RLY, VISIBLE "10"
	MEBBE DIFFRINT INPUT AN BIGGR OF INPUT AN 0 BTW input < 0? 
		INPUT R DIFF OF INPUT AN 3, VISIBLE "INPUT - 3 = "  INPUT
	MEBBE DIFFRINT INPUT AN SMALLR OF INPUT AN 0 BTW input > 0?
		INPUT R PRODUKT OF INPUT AN 2, VISIBLE "INPUT * 2 = " INPUT
OIC
KTHXBYE
